Sp.Map=function(a){this._containerId=a;this.myMeasureGraphicsLayer=this.myTiledMapDemFloatLayer=this.myTiledMapDomFloatLayer=this.myTiledMapServiceLayer=this._mydrawToolbar=this._myMeasureToolbar=this._myNavToolbar=this.map=null;this._curDMapType="dlg";this._list={};this._layerIdList=[];this.extent=null;try{this._containerId!=void 0&&this._containerId!=""&&this._InitMap()}catch(b){throw b;}};
Sp.Map.prototype = { _RaiseEvent: function (a, b) { var c = this.get_events().getHandler(a); if (c) { if (b === null || typeof b === "undefined") b = Sp.EventArgs.Empty; c(this, b) } }, get_events: function () { if (!this._events) this._events = new Sp.EventHandlerList; return this._events }, OnActionBengin: function (a) { this._RaiseEvent("ActionBengin", a) }, OnActionEnd: function (a) { this._RaiseEvent("ActionEnd", a) }, AddActionBengin: function (a) { this.get_events().addHandler("ActionBengin", a) }, RemoveActionBengin: function (a) {
    this.get_events().removeHandler("ActionBengin",
a)
}, AddActionEnd: function (a) { this.get_events().addHandler("ActionEnd", a) }, RemoveActionEnd: function (a) { this.get_events().removeHandler("ActionEnd", a) }, LoadBaseMap: function () {
    esriConfig.defaults.map.slider = { left: "10px", top: "5px", width: null, height: "200px" }; this.myTiledMapServiceLayer = new scgc.layers.SCGISTiledMapServiceLayer(config.dlgmapUrl, { slider: !0, id: "dlgMapLayer", token: config.token }); dojo.connect(this.myTiledMapServiceLayer, "onTokenExpired", Sp.Delegate(this, this._TokenExpired)); this.map.addLayer(this.myTiledMapServiceLayer);
    this.myTiledMapDomFloatLayer = new scgc.layers.SCGISTiledMapServiceLayer(config.dommapUrl, { id: "domFloatMapLayer", visible: !1, token: config.token }); this.map.addLayer(this.myTiledMapDomFloatLayer); dojo.connect(this.myTiledMapDomFloatLayer, "onTokenExpired", Sp.Delegate(this, this._TokenExpired)); this.myTiledMapDemFloatLayer = new scgc.layers.SCGISTiledMapServiceLayer(config.demmapUrl, { id: "demFloatMapLayer", visible: !1, token: config.token }); this.map.addLayer(this.myTiledMapDemFloatLayer); dojo.connect(this.myTiledMapDemFloatLayer,
"onTokenExpired", Sp.Delegate(this, this._TokenExpired)); this._myNavToolbar = new esri.toolbars.Navigation(this.map); this._myMeasureToolbar = new Sp.Measure(this.map); this._mydrawToolbar = new esri.toolbars.Draw(this.map); dojo.connect(this.map, "onLoad", Sp.Delegate(this, this._OnMapLoad))
}, SwitchMap: function () {
    var a = this.GetCurrentMapName(); this.myTiledMapDemFloatLayer.hide(); this.myTiledMapDomFloatLayer.hide(); this.myTiledMapServiceLayer.hide(); a === "dom" ? (this.myTiledMapServiceLayer.switchTileUrl(config.dommapUrl),
this.myTiledMapDemFloatLayer.show(), this.myTiledMapDomFloatLayer.show()) : a === "dlg" && (this.myTiledMapServiceLayer.switchTileUrl(config.dlgmapUrl), this.myTiledMapServiceLayer.show())
}, GetNavToolbar: function () { return this._myNavToolbar }, GetMeasureToolbar: function () { return this._myMeasureToolbar }, GetDrawToolbar: function () { return this._mydrawToolbar }, SetCurrentMapName: function (a) { this._curDMapType = a }, GetCurrentMapName: function () { return this._curDMapType }, GetMap: function () { return this.map }, AddLayer: function (a,
b) { Array.contains(this._layerIdList, a) || (this.map.addLayer(b.myGraphicLayer), Array.add(this._layerIdList, a), this._list[a] = b) }, GetLayer: function (a) { var b = null; Array.contains(this._layerIdList, a) ? b = this._list[a] : (a = this.map.getLayer(a), null != a && this.map.removeLayer(a)); return b }, RemoveLayer: function (a) { Array.contains(this._layerIdList, a) && (this.map.removeLayer(this._list[a].myGraphicLayer), Array.remove(this._layerIdList, a), this._list[a] = void 0) }, RemoveAllLayers: function () {
    Array.forEach(this._layerIdList,
function (a) { this._list[a] = void 0 }, this); Array.clear(this._layerIdList); this.map.removeAllLayers()
}, ShowInfo: function (a, b, c, d) { a = Sp.applyIf(a, { spatialReference: { wkid: 4326} }); a = new esri.geometry.Point(a); this.map.infoWindow.setTitle(b.title); this.map.infoWindow.setContent(b.content); this.map.infoWindow.show(a, this.map.infoWindow._ANCHORS[1]); this.map.infoWindow.resize(c == null ? 200 : c, d == null ? 200 : d);}, ResizeInfo: function (a, b) { this.map.infoWindow.resize(a == null ? 200 : a, b == null ? 200 : b) }, HideInfo: function () { this.map.infoWindow.hide() },
    SetExtent: function (a) { try { a = Sp.applyIf(a, { spatialReference: { wkid: 4326} }), this.map.setExtent(new esri.geometry.Extent(a)) } catch (b) { throw "\u5b9a\u4f4d\u9519\u8bef\uff0c\u8bf7\u68c0\u67e5\u8f93\u5165\u53c2\u6570\u662f\u5426\u6ee1\u8db3\u8981\u6c42\uff01"; } }, Location: function (a, b, c) {
        try { var d = new esri.geometry.Point({ x: a, y: b, spatialReference: { wkid: 4326} }); a = 13; c != null && c > -1 && c <= 18 && (a = c); this.map.setLevel(a); this.map.centerAt(d) } catch (e) {
            throw "\u5b9a\u4f4d\u9519\u8bef\uff0c\u8bf7\u68c0\u67e5\u8f93\u5165\u53c2\u6570\u662f\u5426\u6ee1\u8db3\u8981\u6c42\uff01";
        }
    }, LocationLowerLeft: function (a, b) { try { var c = this.myTiledMapServiceLayer.tileInfo.lods[this.map.getNumLevels() - 1].resolution; a = Sp.applyIf(a, { spatialReference: { wkid: 4326} }); var d = new esri.geometry.Point(a); d.x += c * 185; d.y += c * 120; var e = this.myTiledMapServiceLayer.tileInfo.lods.length; b != null && b > -1 && b <= e && (e = b); this.map.setLevel(e); this.map.centerAt(d) } catch (f) { throw "\u5b9a\u4f4d\u9519\u8bef\uff0c\u8bf7\u68c0\u67e5\u8f93\u5165\u53c2\u6570\u662f\u5426\u6ee1\u8db3\u8981\u6c42\uff01"; } }, ResizeMap: function () {
        null !=
this.map && (this.map.resize(), this.map.reposition())
    }, Destroy: function () { null != this.map && (this.RemoveActionEnd(), this.RemoveAllLayers(), this.map.destroy()) }, _InitMap: function () { this.map = new esri.Map(this._containerId, { logo: !1, extent: new esri.geometry.Extent({ xmin: 101.61567161772264, ymin: 26.519240213774875, xmax: 101.79025123808397, ymax: 26.62721521987839, spatialReference: { wkid: 4326} }) }) }, _OnMapLoad: function () {
        this.myMeasureGraphicsLayer = new esri.layers.GraphicsLayer({ id: "measureGraphicsLayer" }); this.map.addLayer(this.myMeasureGraphicsLayer);
        dojo.connect(this.myMeasureGraphicsLayer, "onClick", this, function (a) { try { a.graphic.attributes.name === "measure_del" && this.myMeasureGraphicsLayer.clear() } catch (b) { } }); this.OnActionEnd(this)
    }, _TokenExpired: function () { config.token == "" ? esri.request({ url: "GetToken.ashx", content: { ST: Math.round(Math.random() * 1E7) }, callbackParamName: "callback", load: Sp.Delegate(this, this._TokenSuccess) }) : (this.myTiledMapServiceLayer.setToken(config.token), this.myTiledMapDomFloatLayer.setToken(config.token), this.myTiledMapDemFloatLayer.setToken(config.token)) },
    _TokenSuccess: function (a) { if (a.success) { var b = a.message.token; config.token = a.message.token; this.myTiledMapServiceLayer.setToken(b); this.myTiledMapDomFloatLayer.setToken(b); this.myTiledMapDemFloatLayer.setToken(b) } }
};  Sp.MapTools={};Sp.MapTools.BaseTool=function(a){this._spMap=a};
Sp.MapTools.BaseTool.prototype={_RaiseEvent:function(a,b){var c=this.get_events().getHandler(a);if(c){if(b===null||typeof b==="undefined")b=Sp.EventArgs.Empty;c(this,b)}},get_events:function(){if(!this._events)this._events=new Sp.EventHandlerList;return this._events},GetMap:function(){return this._spMap},SetMap:function(){this._spMap=_spMap},Execute:function(a){null==this._spMap?alert("\u6ca1\u8bbe\u7f6e\u5730\u56fe\u5bf9\u8c61\uff0c\u4e0d\u80fd\u6267\u884c\u5de5\u5177"):this.OnExecute(a)},Deactive:function(a){this.OnDeactive(a)},
OnExecute:function(){},OnDeactive:function(){},OnActionBengin:function(a){this._RaiseEvent("ActionBengin",a)},OnActionEnd:function(a){this._RaiseEvent("ActionEnd",a)},AddActionBengin:function(a){this.get_events().addHandler("ActionBengin",a)},RemoveActionBengin:function(a){this.get_events().removeHandler("ActionBengin",a)},AddActionEnd:function(a){this.get_events().addHandler("ActionEnd",a)},RemoveActionEnd:function(a){this.get_events().removeHandler("ActionEnd",a)}};
Sp.MapTools.ZoomIn=Sp.extend(Sp.MapTools.BaseTool,{constructor:function(a){Sp.MapTools.ZoomIn.superclass.constructor.apply(this,[a])},OnExecute:function(){this.GetMap().GetNavToolbar().activate(esri.toolbars.Navigation.ZOOM_IN)}});Sp.MapTools.ZoomOut=Sp.extend(Sp.MapTools.BaseTool,{constructor:function(a){Sp.MapTools.ZoomOut.superclass.constructor.apply(this,[a])},OnExecute:function(){this.GetMap().GetNavToolbar().activate(esri.toolbars.Navigation.ZOOM_OUT)}});
Sp.MapTools.Pan=Sp.extend(Sp.MapTools.BaseTool,{constructor:function(a){Sp.MapTools.Pan.superclass.constructor.apply(this,[a])},OnExecute:function(){this.GetMap().GetNavToolbar().activate(esri.toolbars.Navigation.PAN)}});Sp.MapTools.LengthTool=Sp.extend(Sp.MapTools.BaseTool,{constructor:function(a){Sp.MapTools.LengthTool.superclass.constructor.apply(this,[a])},OnExecute:function(){this.GetMap().GetMeasureToolbar().activate(Measurename.measure_length)}});
Sp.MapTools.AreaTool=Sp.extend(Sp.MapTools.BaseTool,{constructor:function(a){Sp.MapTools.AreaTool.superclass.constructor.apply(this,[a])},OnExecute:function(){this.GetMap().GetMeasureToolbar().activate(Measurename.measure_area)}});Sp.MapTools.DrawTool=Sp.extend(Sp.MapTools.BaseTool,{constructor:function(a){Sp.MapTools.DrawTool.superclass.constructor.apply(this,[a]);this._graphicLayerId="tempGraphicLayer"},SetGraphicLayerId:function(a){this._graphicLayerId=a},GetGraphicLayerId:function(){return this._graphicLayerId}});
Sp.MapTools.PointTool=Sp.extend(Sp.MapTools.DrawTool,{constructor:function(a){Sp.MapTools.PointTool.superclass.constructor.apply(this,[a]);this.OnDrawEndHandler=this._point=this._drawToolbar=null},OnExecute:function(){this._drawToolbar=this.GetMap().GetDrawToolbar();this.OnDrawEndHandler=dojo.connect(this._drawToolbar,"onDrawEnd",Sp.Delegate(this,this._OnDrawEnd));this._drawToolbar.activate(esri.toolbars.Draw.POINT)},OnDeactive:function(){this._dispose()},GetPoint:function(){return this._point},_OnDrawEnd:function(a){this._point=
{x:a.x,y:a.y};this._RaiseActionEnd();this._dispose()},_RaiseActionEnd:function(){this.OnActionEnd({Feature:this._point})},_dispose:function(){this.GetMap();if(null!=this.OnDrawEndHandler)dojo.disconnect(this.OnDrawEndHandler),this.OnDrawEndHandler=null;null!=this._drawToolbar&&this._drawToolbar.deactivate()}});
Sp.MapTools.PolygonTool=Sp.extend(Sp.MapTools.DrawTool,{constructor:function(a){Sp.MapTools.PolygonTool.superclass.constructor.apply(this,[a]);this.OnDrawEndHandler=this._polygon=this._drawToolbar=null},OnExecute:function(){this._drawToolbar=this.GetMap().GetDrawToolbar();this.OnDrawEndHandler=dojo.connect(this._drawToolbar,"onDrawEnd",Sp.Delegate(this,this._OnDrawEnd));this._drawToolbar.activate(esri.toolbars.Draw.POLYGON)},OnDeactive:function(){this._dispose()},GetPoint:function(){return this._polygon},
_OnDrawEnd:function(a){this._polygon=a.rings;this._RaiseActionEnd();this._dispose()},_RaiseActionEnd:function(){this.OnActionEnd({Feature:this._polygon})},_dispose:function(){this.GetMap();if(null!=this.OnDrawEndHandler)dojo.disconnect(this.OnDrawEndHandler),this.OnDrawEndHandler=null;null!=this._drawToolbar&&this._drawToolbar.deactivate()}});
Sp.MapTools.RectangleTool=Sp.extend(Sp.MapTools.DrawTool,{constructor:function(a){Sp.MapTools.RectangleTool.superclass.constructor.apply(this,[a]);this.OnDrawEndHandler=this._Extent=this._drawToolbar=null},OnExecute:function(){this._drawToolbar=this.GetMap().GetDrawToolbar();this.OnDrawEndHandler=dojo.connect(this._drawToolbar,"onDrawEnd",Sp.Delegate(this,this._OnDrawEnd));this._drawToolbar.activate(esri.toolbars.Draw.EXTENT)},OnDeactive:function(){this._dispose()},GetExtent:function(){return this._Extent},
_OnDrawEnd:function(a){this._Extent={xmin:a.xmin,ymin:a.ymin,xmax:a.xmax,ymax:a.ymax};this._RaiseActionEnd();this._dispose()},_RaiseActionEnd:function(){this.OnActionEnd({Feature:this._Extent})},_dispose:function(){this.GetMap();if(null!=this.OnDrawEndHandler)dojo.disconnect(this.OnDrawEndHandler),this.OnDrawEndHandler=null;null!=this._drawToolbar&&this._drawToolbar.deactivate()}});Sp.Measure=function(a){this.map=a;this.measureEnd=null;this.currentTool="";this.draw=new esri.toolbars.Draw(this.map,{showTooltips:!1});this.font=(new esri.symbol.Font).setSize("12pt").setWeight(esri.symbol.Font.WEIGHT_BOLD);this.linesym=new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,new dojo.Color([50,50,50,0.7]),2);this.areasym=new esri.symbol.SimpleFillSymbol(esri.symbol.SimpleFillSymbol.STYLE_SOLID,new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,
new dojo.Color([98,194,204]),2),new dojo.Color([98,194,204,0.5]));this.delsym=new esri.symbol.PictureMarkerSymbol(config.measure_delete,20,33);this.delsym.xoffset=0;this.delsym.yoffset=15;this.draw.setLineSymbol(this.linesym);this.draw.setFillSymbol(this.areasym);this.activate=function(a){this.currentTool=a;this.currentTool==Measurename.measure_length?this.draw.activate(esri.toolbars.Draw.POLYLINE):this.currentTool==Measurename.measure_area&&this.draw.activate(esri.toolbars.Draw.POLYGON)};this.deactivate=
function(){this.draw.deactivate()};this.addToMap=function(a){var c=this.map.getLayer("measureGraphicsLayer");c.clear();if(this.currentTool==Measurename.measure_length){var d=new esri.Graphic(a,this.linesym);c.add(d);var e=GeoCoordinate2ProjCoordinate(a.paths[0]);d=CalcLens(e);e=e.length;for(var f=0,g=1;g<e;g++){var i=a.getPoint(0,g);f+=d[g-1];f=Math.round(f*100)/100;var h=f+" \u7c73";f/1E3>1&&(h=Math.round(f/10)/100+" \u5343\u7c73");h=new esri.symbol.TextSymbol(h,this.font,new dojo.Color([255,0,0]));
i=new esri.Graphic(i,h,{});c.add(i)}}else this.currentTool==Measurename.measure_area&&(d=new esri.Graphic(a,this.areasym),c.add(d),e=GeoCoordinate2ProjCoordinate(a.rings[0]),d=CalcArea(e),d=Math.round(d*100)/100,e=a.getExtent().getCenter(),h=d+" \u5e73\u65b9\u7c73",d/1E6>1&&(h=Math.round(d/1E4)/100+" \u5e73\u65b9\u5343\u7c73"),d=new esri.symbol.TextSymbol(h,this.font,new dojo.Color([255,0,0])),d=new esri.Graphic(e,d,{}),c.add(d));a=new esri.Graphic(a.getPoint(0,0),this.delsym,{name:"measure_del"});
c.add(a)};this.measure_length="measure_length";this.measure_area="measure_area";dojo.connect(this.draw,"onDrawEnd",this,this.addToMap);return this};Measurename={measure_length:"measure_length",measure_area:"measure_area"};function CalcLens(a){var b=[];if(a!=null)for(var c=1;c<a.length;c++){var d=a[c-1],e=a[c];b.push(Math.sqrt(Math.pow(d[0]-e[0],2)+Math.pow(d[1]-e[1],2)))}else b.push(0);return b}
function CalcArea(a){if(a==null||a.length<3)return 0;var b=a[0],c=a[a.length-1];try{var d=b[0]==c[0]&&b[1]==c[1]?a.length-1:a.length;c=0;for(var e=1;e<d-1;e++){var f=a[e],g=a[e+1];c+=b[0]*f[1]-b[1]*f[0]+b[1]*g[0]-b[0]*g[1]+f[0]*g[1]-g[0]*f[1]}return Math.abs(c/2)}catch(i){}return 0}
function GeoCoordinate2ProjCoordinate(a){for(var b=0,c=[],d=0;d<a.length;d++){var e=a[d],f=[];f[0]=ComputeMeridian(Deg2Rad(e[0]),Deg2Rad(e[1]));d==0?(f[1]=0,b=Deg2Rad(e[0])):f[1]=ComputeRadian(Deg2Rad(e[0])-b,Deg2Rad(e[1]));c.push(f)}return c}function Deg2Rad(a){return a*Math.PI/180}function ComputeMeridian(a,b){return 6367452.2597*b-16038.528*Math.sin(2*b)+16.833*Math.sin(4*b)-0.022*Math.sin(6*b)}
function ComputeRadian(a,b){return 6378140*Math.cos(b)*a/Math.sqrt(1-0.006694384999588*Math.pow(Math.sin(b),2))};Sp.UtilityTools=function(a){this._spMap=a;this._tool=null};
Sp.UtilityTools.prototype={ZoomIn:function(){this.Dispose();this._tool=new Sp.MapTools.ZoomIn(this._spMap);this._tool.Execute()},ZoomOut:function(){this.Dispose();this._tool=new Sp.MapTools.ZoomOut(this._spMap);this._tool.Execute()},Pan:function(){this.Dispose();this._tool=new Sp.MapTools.Pan(this._spMap);this._tool.Execute()},LengthTool:function(){this.Dispose();this._tool=new Sp.MapTools.LengthTool(this._spMap);this._tool.Execute()},AreaTool:function(){this.Dispose();this._tool=new Sp.MapTools.AreaTool(this._spMap);
this._tool.Execute()},SetTool:function(a,b){this.Dispose();null!=Sp.MapTools[a]?(this._tool=new Sp.MapTools[a](this._spMap),Sp.isFunction(b)&&this._tool.AddActionEnd(b),this._tool.Execute()):Sp.Msg.alert("\u8be5\u5de5\u5177\u6ca1\u6709\u5b9a\u4e49\uff0c\u4e0d\u80fd\u6267\u884c\u5de5\u5177","error")},Dispose:function(){var a=this._spMap.GetNavToolbar();null!=a&&a.deactivate();var b=this._spMap.GetMeasureToolbar();null!=a&&b.deactivate();if(null!=this._tool&&null!=this._tool.Deactive)this._tool.Deactive(),
this._tool=null}};Sp.GraphicLayer=function(a,b){this.map=a;b=b==null?{}:b;this._layerId=b.id==""?"tempLayer":b.id;this.myGraphicLayer=null;this._eventName=[];this._eventList={};this._InitLayer()};
Sp.GraphicLayer.prototype={AddEvent:function(a,b){Array.contains(this._eventName,a)||(Array.add(this._eventName,a),null!=this.myGraphicLayer&&(this._eventList[a]=dojo.connect(this.myGraphicLayer,a,b)))},RemoveEvent:function(a){dojo.disconnect(this._eventList[a]);Array.remove(this._eventName,a);this._eventList[a]=void 0},RemoveAllEvent:function(){Array.forEach(this._eventName,function(a){dojo.disconnect(this._eventList[a]);this._eventList[a]=void 0},this);Array.clear(this._eventName)},AddPictureMarkerGraphic:function(a,
b,c,d){d=d==null?{}:d;a=Sp.applyIf(a,{spatialReference:{wkid:4326}});a=new esri.geometry.Point(a);b=new esri.symbol.PictureMarkerSymbol(b);b=new esri.Graphic(a,b,d);if(null!=c)c=new esri.InfoTemplate(c.title,c.content),b.infoTemplate=c;this.myGraphicLayer.add(b)},AddMarkerGraphic:function(a,b,c){a=new esri.geometry.Point({x:a,y:b,spatialReference:{wkid:4326}});b=new esri.symbol.SimpleMarkerSymbol(esri.symbol.SimpleMarkerSymbol.STYLE_DIAMOND,10,new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,
new dojo.Color([233,80,174]),1),new dojo.Color([208,232,126,0.8]));b=new esri.Graphic(a,b);if(null!=c){var d=new esri.InfoTemplate(c.title,c.content);b.infoTemplate=d;this._ShowInfo(a,d,c.height,c.width)}this.myGraphicLayer.add(b)},AddTextGraphic:function(){},AddPolygonGraphic:function(a,b,c,d){d=d==null?{}:d;a=Sp.applyIf(a,{spatialReference:{wkid:4326}});a=new esri.Graphic({geometry:a,symbol:b,attributes:d});if(null!=c)c=new esri.InfoTemplate(c.title,c.content),a.infoTemplate=c;this.myGraphicLayer.add(a)},
SwitchGeometry:function(a){try{for(var b=0;b<a.length;b++){var c=this.GetGraphicByAttr(a[b].key,a[b].value),d=null,e=null;switch(c.geometry.type){case "polygon":d=new esri.geometry.Polygon(Sp.applyIf(a[b].geometry,{spatialReference:{wkid:4326}}));e=d.getExtent().getCenter();break;case "point":e=d=new esri.geometry.Point(Sp.applyIf(a[b].geometry,{spatialReference:{wkid:4326}}));break;default:throw"\u73b0\u5728\u53ea\u652f\u6301\u9762\u548c\u70b9\u7684\u4f4d\u7f6e\u5207\u6362,\u82e5\u8981\u652f\u6301\u5176\u4ed6\u7c7b\u578b\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458\uff01";
}c.setGeometry(d);var f=this.map.GetMap().infoWindow;f.isShowing&&f.show(e,f._ANCHORS[1])}}catch(g){throw"\u8bf7\u68c0\u67e5\u8f93\u5165\u53c2\u6570\u662f\u5426\u6b63\u786e\uff01";}},GetGraphicByAttr:function(a,b){for(var c=this.myGraphicLayer.graphics,d=null,e=0;e<c.length;e++){var f=c[e];if(f.attributes[a]==b){d=f;break}}return d},RemoveGraphic:function(){},ClearGraphic:function(){this.myGraphicLayer.clear()},_InitLayer:function(){this.myGraphicLayer=new esri.layers.GraphicsLayer({id:this._layerId,
displayOnPan:!0})}};
